FROM python:3.9-slim as builder

WORKDIR /home/app
RUN apt-get update \
    && apt-get install -y git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache --target=/home/app/dependencies fastapi uvicorn \
    && pip install --no-cache --target=/home/app/dependencies "git+https://github.com/made-ml-in-prod-2022/FiliVan@homework1_last#egg=ml_project&subdirectory=ml_project" 

FROM python:3.9-slim

WORKDIR /home/app
COPY --from=builder /home/app .
COPY app_v2.py .

ENV PYTHONPATH="${PYTHONPATH}:/home/app/dependencies"
ENV PATH_TO_MODEL="https://drive.google.com/file/d/1oGfWKZVbueiiMZ1L2f_BqDv0oiIE3uH8/view?usp=sharing"

CMD ["python", "app_v2.py"]