apiVersion: v1
kind: ReplicaSet
metadata:
  name: online-inference-replica
  labels:
    app: online-inference-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-inference-replica
  template:
    metadata:
      name: online-inference-replica
      labels:
        app: online-inference-replica
    spec:
      containers:
        - image: filivan/online_inference:latest
          name: online-inference
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5