defaults:
  - _self_
  - model: rf_model
  - general: general

output_model_path: models/model.pkl
metric_path: models/metrics.json
downloading_params:
  gdrive_id: 1Q0JMqL54o6VCJ0tkMvb6jIzyPFJjy0FQ
  output_folder: data/raw/
splitting_params:
  val_size: 0.2
  random_state: ${general.random_state}
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "condition"
transform_params:
  ohe_categorical: True
  normilize_numerical: True 
mlflow_params:
  mlflow_uri: mlruns 
  mlflow_experiment: ml_project

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
